import styles from './styles.module.scss'
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Dancing_Script, Josefin_Sans, Nunito } from 'next/font/google';
import Navbar from "./components/navbar/page";
import Header from "./components/header/page";
import "./globals.scss";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className={styles.layout}>
          <div><Header /></div>
          <div className={styles.middle}>
            <div className={styles.navbar}>
              <Navbar />
            </div>
            {/* <div style={{
              width: '100%',
              margin: '1rem',
              display: 'flex',
              flexDirection: 'column',
              height: '100%',
              overflowY: 'auto',
              // backgroundColor: 'red',
            }}> */}
            <div className={styles.main}>
              {children}
            </div>
          </div>
        </div>
      </body>
    </html >
  );
}
